const express=require('express');
const session=require('express-session');
const bcrypt=require('bcryptjs');
const multer=require('multer');
const path=require('path');
const fs=require('fs');
require('dotenv').config();

const app=express();
const PORT=Number(process.env.PORT||3000);
const ROOT=__dirname;
const DATA=path.join(ROOT,'data');
const UP=path.join(ROOT,'uploads');
const PAYMENT=path.join(UP,'payment');
const RESULTS=path.join(UP,'results');
for(const d of [DATA,UP,PAYMENT,RESULTS])fs.mkdirSync(d,{recursive:true});
const DB=path.join(DATA,'db.json');
const now=()=>new Date().toISOString();
const monthKey=()=>{const d=new Date();return d.toISOString().slice(0,7)};
function load(){if(!fs.existsSync(DB))return {users:[],services:[],walletRequests:[],walletLedger:[],requests:[],messages:[],settings:{upiId:process.env.UPI_ID||'rjnpancenter@naviaxis'}};return JSON.parse(fs.readFileSync(DB,'utf8'))}
let db=load();
function save(){const tmp=DB+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DB)}
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const safeUser=u=>({id:u.id,name:u.name,email:u.email,phone:u.phone,role:u.role,wallet:u.wallet||0,createdAt:u.createdAt});
function seed(){
 if(!db.settings)db.settings={upiId:process.env.UPI_ID||'rjnpancenter@naviaxis'};
 if(!db.users.some(u=>u.role==='admin'))db.users.push({id:id(),name:'RJN Admin',email:(process.env.ADMIN_EMAIL||'admin@rjnprintportal.local').toLowerCase(),phone:'',passwordHash:bcrypt.hashSync(process.env.ADMIN_PASSWORD||'ChangeMe123!',12),role:'admin',wallet:0,createdAt:now()});
 if(db.services.length)return;
 const add=(name,price,description,fields,documents)=>db.services.push({id:id(),name,price,description,icon:'📄',enabled:true,fields,documents,instructions:'Submit only information and documents you are authorized to provide.',createdAt:now()});
 add('Aadhaar to PAN Find',25,'Aadhaar based manual request',[['aadhaar','Aadhaar Number','text',true]],[]);
 add('PAN Details Find',15,'PAN details manual request',[['pan','PAN Number','text',true]],[]);
 add('PAN Verification',15,'PAN verification request',[['pan','PAN Number','text',true]],[]);
 add('Voter Mobile Link',25,'Manual voter mobile-link request',[['epic','EPIC / Voter ID','text',true],['mobile','Mobile Number','tel',true]],[]);
 add('Voter PDF With Download',6,'Manual voter PDF request',[['epic','EPIC / Voter ID','text',true]],[]);
 add('PAN to Aadhaar Find',25,'PAN to Aadhaar manual request',[['pan','PAN Number','text',true]],[]);
 add('GST Details',10,'GST details request',[['gstin','GSTIN','text',true]],[]);
 add('Assam Ration to Aadhaar',70,'Manual ration/Aadhaar request',[['ration','Assam Ration Card Number','text',true]],[]);
 add('Ration No. to PDF',20,'Ration PDF request',[['ration','Ration Card Number','text',true],['design','Card Design Type','text',true]],[]);
 add('E-Shram PDF Download',10,'E-Shram PDF request',[['eshram','E-Shram Number','text',true]],[]);
 add('NPCI Status',10,'NPCI status request',[['aadhaar','Aadhaar Number','text',true]],[]);
 add('Mobile No. to PAN Find',10,'Mobile to PAN request',[['mobile','Mobile Number','tel',true]],[]);
 add('PAN Manual',15,'Manual PAN service',[['pan','PAN Number','text',true],['name','Name','text',true],['father','Father Name','text',false],['dob','Date of Birth','date',true],['gender','Gender','select',true]],['Photo','Signature']);
 add('Aadhaar Manual',20,'Manual Aadhaar service',[['aadhaar','Aadhaar Number','text',true],['name','Name','text',true],['father','Father Name','text',true],['house','House No.','text',false],['locality','Gali / Locality','text',true],['post','Post Office','text',true],['state','State','text',true],['city','City','text',true],['pin','PIN Code','text',true],['dob','Date of Birth','date',true],['gender','Gender','select',true],['address','Address','textarea',true]],['Photo']);
 add('Voter Manual Instant',15,'Manual voter service',[['epic','EPIC Number','text',false],['full_name_en','Full Name (English)','text',true],['full_name_local','Full Name (Local)','text',false],['relation','Relation Type','select',true],['relative_en','Father/Mother Name','text',false],['dob','Date of Birth','date',true],['gender','Gender','select',true],['address_en','Address','textarea',true]],['Voter Photo']);
 add('Voter Manual New',15,'New voter manual application',[['full_name','Full Name','text',true],['dob','Date of Birth','date',true],['gender','Gender','select',true],['address','Address','textarea',true],['mobile','Mobile Number','tel',false]],['Voter Photo','Identity/Address Document']);
 add('RTPS Services',10,'Manual RTPS request',[['service_type','RTPS Service Type','text',true],['name','Applicant Name','text',true],['mobile','Mobile Number','tel',true],['details','Application Details','textarea',true]],['Supporting Document']);
 save();
}
seed();
app.use(express.json({limit:'3mb'}));
app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||'rjn-local-change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',maxAge:8*60*60*1000}}));
app.use(express.static(path.join(ROOT,'public')));
const disk=multer.diskStorage({destination:(req,file,cb)=>cb(null,file.fieldname==='result'?RESULTS:PAYMENT),filename:(req,file,cb)=>cb(null,id()+path.extname(file.originalname||''))});
const upload=multer({storage:disk,limits:{fileSize:10*1024*1024}});
const auth=(req,res,next)=>{const u=db.users.find(x=>x.id===req.session.userId);if(!u)return res.status(401).json({error:'Login required'});req.user=u;next()};
const admin=(req,res,next)=>{if(req.user?.role!=='admin')return res.status(403).json({error:'Admin only'});next()};
const customer=(req,res,next)=>{if(req.user?.role!=='customer')return res.status(403).json({error:'Customer only'});next()};
const publicService=s=>({...s,price:Number(s.price),fields:s.fields||[],documents:s.documents||[]});
app.get('/api/me',(req,res)=>{const u=db.users.find(x=>x.id===req.session.userId);res.json({user:u?safeUser(u):null,settings:{upiId:db.settings.upiId}})});
app.post('/api/register',(req,res)=>{try{const {name,phone,email,password}=req.body;if(!name||!phone||!email||!password)return res.status(400).json({error:'Name, mobile, email and password are required'});if(String(password).length<8)return res.status(400).json({error:'Password must be at least 8 characters'});const e=String(email).trim().toLowerCase(),p=String(phone).trim();if(db.users.some(u=>u.email===e||u.phone===p))return res.status(400).json({error:'Email or mobile already registered'});const u={id:id(),name:String(name).trim(),phone:p,email:e,passwordHash:bcrypt.hashSync(password,12),role:'customer',wallet:0,createdAt:now()};db.users.push(u);save();req.session.userId=u.id;res.json({user:safeUser(u)})}catch(e){res.status(400).json({error:'Registration failed'})}});
app.post('/api/login',(req,res)=>{const key=String(req.body.identifier||'').trim().toLowerCase(),u=db.users.find(x=>x.email===key||x.phone===String(req.body.identifier||'').trim());if(!u||!bcrypt.compareSync(String(req.body.password||''),u.passwordHash))return res.status(401).json({error:'Invalid email/mobile or password'});req.session.userId=u.id;res.json({user:safeUser(u)})});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/services',(req,res)=>res.json(db.services.filter(s=>s.enabled).map(publicService)));
app.get('/api/customer/stats',auth,customer,(req,res)=>{const mine=db.requests.filter(r=>r.userId===req.user.id);res.json({wallet:req.user.wallet||0,total:mine.length,pending:mine.filter(r=>['Pending','Processing'].includes(r.status)).length,completed:mine.filter(r=>r.status==='Completed').length,upiId:db.settings.upiId})});
app.post('/api/wallet/request',auth,customer,upload.single('proof'),(req,res)=>{const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Enter a valid amount'});const utr=String(req.body.utr||'').trim();if(!utr)return res.status(400).json({error:'UTR / transaction ID is required'});if(db.walletRequests.some(w=>w.utr===utr&&['Pending','Approved'].includes(w.status)))return res.status(400).json({error:'This UTR is already submitted'});db.walletRequests.push({id:id(),userId:req.user.id,amount,utr,proofFile:req.file?.filename||null,status:'Pending',createdAt:now(),month:monthKey()});save();res.json({ok:true})});
app.get('/api/customer/wallet',(req,res)=>{if(!req.user)return res.status(401).json({error:'Login required'});res.json(db.walletRequests.filter(w=>w.userId===req.user.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,30))});
app.post('/api/service/:sid/request',auth,customer,upload.array('files',10),(req,res)=>{const s=db.services.find(x=>x.id===req.params.sid&&x.enabled);if(!s)return res.status(404).json({error:'Service not found'});const data=JSON.parse(req.body.data||'{}');for(const f of s.fields||[])if(f[3]&&!String(data[f[0]]||'').trim())return res.status(400).json({error:'Required field: '+f[1]});if((req.user.wallet||0)<Number(s.price))return res.status(400).json({error:'Insufficient wallet balance'});const files=(req.files||[]).map(f=>({file:f.filename,name:f.originalname}));req.user.wallet=Number(req.user.wallet)-Number(s.price);const r={id:id(),userId:req.user.id,serviceId:s.id,data,fee:Number(s.price),status:'Pending',inputFiles:files,resultFile:null,resultName:null,createdAt:now(),completedAt:null,expiresAt:null,refunded:false};db.requests.push(r);db.walletLedger.push({id:id(),userId:req.user.id,type:'DEBIT',amount:Number(s.price),requestId:r.id,createdAt:now(),note:'Service charge: '+s.name});save();res.json({ok:true,wallet:req.user.wallet,requestId:r.id})});
app.get('/api/customer/requests',auth,customer,(req,res)=>res.json(db.requests.filter(r=>r.userId===req.user.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(r=>{const s=db.services.find(x=>x.id===r.serviceId);return {...r,serviceName:s?.name||'Service',resultAvailable:!!r.resultFile&&(!r.expiresAt||new Date(r.expiresAt)>new Date())}})));
app.get('/api/result/:rid',auth,customer,(req,res)=>{const r=db.requests.find(x=>x.id===req.params.rid&&x.userId===req.user.id);if(!r||!r.resultFile)return res.status(404).send('Result not available');if(r.expiresAt&&new Date(r.expiresAt)<new Date())return res.status(410).send('File expired');const p=path.join(RESULTS,r.resultFile);if(!fs.existsSync(p))return res.status(404).send('File expired');res.download(p,r.resultName||'result')});
app.get('/api/chat',auth,(req,res)=>res.json(db.messages.filter(m=>m.userId===req.user.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).slice(-100)));
app.post('/api/chat',auth,upload.single('attachment'),(req,res)=>{const text=String(req.body.message||'').trim();if(!text&&!req.file)return res.status(400).json({error:'Message is empty'});db.messages.push({id:id(),userId:req.user.id,from:req.user.role,text,attachment:req.file?{file:req.file.filename,name:req.file.originalname}:null,createdAt:now(),read:false});save();res.json({ok:true})});
// Admin
app.get('/api/admin/dashboard',auth,admin,(req,res)=>{const customers=db.users.filter(u=>u.role==='customer');const today=new Date().toISOString().slice(0,10);res.json({customers:customers.length,active:customers.length,todayRegistrations:customers.filter(u=>u.createdAt.startsWith(today)).length,monthRegistrations:customers.filter(u=>u.createdAt.startsWith(monthKey())).length,pendingWallet:db.walletRequests.filter(w=>w.status==='Pending').length,pendingRequests:db.requests.filter(r=>['Pending','Processing'].includes(r.status)).length,services:db.services.length})});
app.get('/api/admin/customers',auth,admin,(req,res)=>res.json(db.users.filter(u=>u.role==='customer').sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(safeUser)));
app.get('/api/admin/services',auth,admin,(req,res)=>res.json(db.services.map(publicService)));
app.post('/api/admin/services',auth,admin,(req,res)=>{const b=req.body;if(!b.name)return res.status(400).json({error:'Service name required'});const s={id:id(),name:String(b.name),price:Number(b.price)||0,description:String(b.description||''),icon:String(b.icon||'📄'),enabled:b.enabled!==false,fields:b.fields||[],documents:b.documents||[],instructions:String(b.instructions||''),createdAt:now()};db.services.push(s);save();res.json(s)});
app.put('/api/admin/services/:id',auth,admin,(req,res)=>{const s=db.services.find(x=>x.id===req.params.id);if(!s)return res.status(404).json({error:'Service not found'});Object.assign(s,{name:String(req.body.name||s.name),price:Number(req.body.price)||0,description:String(req.body.description||''),icon:String(req.body.icon||'📄'),enabled:req.body.enabled!==false,fields:req.body.fields||[],documents:req.body.documents||[],instructions:String(req.body.instructions||'')});save();res.json(s)});
app.delete('/api/admin/services/:id',auth,admin,(req,res)=>{const s=db.services.find(x=>x.id===req.params.id);if(!s)return res.status(404).json({error:'Not found'});s.enabled=false;save();res.json({ok:true})});
app.get('/api/admin/wallet',auth,admin,(req,res)=>res.json(db.walletRequests.filter(w=>w.month===monthKey()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(w=>({...w,customer:db.users.find(u=>u.id===w.userId)?.name||'Unknown'}))));
app.post('/api/admin/wallet/:id/approve',auth,admin,(req,res)=>{const w=db.walletRequests.find(x=>x.id===req.params.id&&x.status==='Pending');if(!w)return res.status(404).json({error:'Request not found'});const u=db.users.find(x=>x.id===w.userId);w.status='Approved';u.wallet=Number(u.wallet||0)+Number(w.amount);db.walletLedger.push({id:id(),userId:u.id,type:'CREDIT',amount:Number(w.amount),walletRequestId:w.id,createdAt:now(),note:'Wallet add-money approved'});save();res.json({ok:true})});
app.post('/api/admin/wallet/:id/reject',auth,admin,(req,res)=>{const w=db.walletRequests.find(x=>x.id===req.params.id&&x.status==='Pending');if(!w)return res.status(404).json({error:'Request not found'});w.status='Rejected';save();res.json({ok:true})});
app.delete('/api/admin/wallet/:id/proof',auth,admin,(req,res)=>{const w=db.walletRequests.find(x=>x.id===req.params.id);if(!w)return res.status(404).json({error:'Not found'});if(w.proofFile){const p=path.join(PAYMENT,w.proofFile);if(fs.existsSync(p))fs.unlinkSync(p);w.proofFile=null;save()}res.json({ok:true})});
app.get('/api/admin/requests',auth,admin,(req,res)=>res.json(db.requests.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(r=>({...r,customer:db.users.find(u=>u.id===r.userId)?.name||'Unknown',serviceName:db.services.find(s=>s.id===r.serviceId)?.name||'Service'}))));
app.post('/api/admin/request/:id/process',auth,admin,upload.single('result'),(req,res)=>{const r=db.requests.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:'Request not found'});const status=String(req.body.status||'Processing');if(!['Processing','Completed','Rejected'].includes(status))return res.status(400).json({error:'Invalid status'});if(status==='Rejected'&&!r.refunded){const u=db.users.find(x=>x.id===r.userId);u.wallet=Number(u.wallet||0)+Number(r.fee);r.refunded=true;db.walletLedger.push({id:id(),userId:u.id,type:'REFUND',amount:Number(r.fee),requestId:r.id,createdAt:now(),note:'Automatic refund for rejected service'});}if(status==='Completed'){if(req.file){r.resultFile=req.file.filename;r.resultName=req.file.originalname}else if(!r.resultFile)return res.status(400).json({error:'Upload result file to complete this request'});r.completedAt=now();r.expiresAt=new Date(Date.now()+30*24*60*60*1000).toISOString()}r.status=status;save();res.json({ok:true})});
app.get('/api/admin/chat/users',auth,admin,(req,res)=>{const ids=[...new Set(db.messages.map(m=>m.userId))];res.json(ids.map(uid=>{const u=db.users.find(x=>x.id===uid);return u?{...safeUser(u),unread:db.messages.filter(m=>m.userId===uid&&m.from==='customer'&&!m.read).length}:null}).filter(Boolean))});
app.get('/api/admin/chat/:uid',auth,admin,(req,res)=>res.json(db.messages.filter(m=>m.userId===req.params.uid).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).slice(-100)));
app.post('/api/admin/chat/:uid',auth,admin,upload.single('attachment'),(req,res)=>{const text=String(req.body.message||'').trim();if(!text&&!req.file)return res.status(400).json({error:'Message empty'});db.messages.push({id:id(),userId:req.params.uid,from:'admin',text,attachment:req.file?{file:req.file.filename,name:req.file.originalname}:null,createdAt:now(),read:true});db.messages.filter(m=>m.userId===req.params.uid&&m.from==='customer').forEach(m=>m.read=true);save();res.json({ok:true})});
app.get('/api/attachment/:mid',auth,(req,res)=>{const m=db.messages.find(x=>x.id===req.params.mid);if(!m||!m.attachment)return res.status(404).end();if(req.user.role!=='admin'&&m.userId!==req.user.id)return res.status(403).end();const p=path.join(PAYMENT,m.attachment.file);if(!fs.existsSync(p))return res.status(404).end();res.download(p,m.attachment.name)});
app.post('/api/admin/settings',auth,admin,(req,res)=>{db.settings.upiId=String(req.body.upiId||db.settings.upiId);save();res.json(db.settings)});
setInterval(()=>{let changed=false;for(const r of db.requests){if(r.resultFile&&r.expiresAt&&new Date(r.expiresAt)<new Date()){const p=path.join(RESULTS,r.resultFile);if(fs.existsSync(p))fs.unlinkSync(p);r.resultFile=null;r.resultName=null;changed=true}}if(changed)save()},60*60*1000);
app.listen(PORT,()=>console.log(`RJN PRINT PORTAL running at http://localhost:${PORT}`));
